### PR TITLE
Fix CI failure

### PR DESCRIPTION
**Pull request by notgull**

### CODE REVIEW

**Comment by zesterer** [comment]
Looks like there's still a failure :( https://github.com/mvdnes/spin-rs/actions/runs/3220728435/workflow

**Comment by notgull** [comment]
MIRI appears to be failing due to one of the tests leaving a thread hanging before exiting. This can be fixed by adding a sleep operation to the end of the offending test to give it time to catch up.

**Comment by notgull** [comment]
Not sure, I just set it up to ignore threading leaks for the time being.

**Comment by zesterer** [comment]
Thanks, I think that's satisfactory for now. This is still a substantial improvement, so thanks!

**Pull request merged**
