### PR TITLE
Fix build on rustc nightly-2017-09-16

### PR DESCRIPTION
**Pull request by messense**
Caused by https://github.com/rust-lang/rust/pull/43017

### CODE REVIEW

**Comment by Ericson2314** [comment]
Can this be merged?

**Comment by mvdnes** [comment]
Thanks for the fix! 👍

**Comment by ids1024** [comment]
@mvdnes You should do a release, since this crate is currently broken with recent compilers.

**Comment by mvdnes** [comment]
Done

**Pull request merged**
