### PR TITLE
Added support for the atomic-polyfill crate

### PR DESCRIPTION
**Pull request by Wassasin**
Proposal to implement #114.

### CODE REVIEW

**Comment by zesterer** [comment]
I appreciate the MR, but I still don't think I'm happy to merge this in its current state. It's just too easy for a dependency somewhere to accidentally turn on polyfill, triggering UB in unrelated parts of the codebase. Cargo features are intended to be strictly additive, and this change violates that principle at a contractual level, even if not at an API level.

I'm not sure how to progress around this barrier. This is a useful feature, but I'm not willing to see it merged when it has the potential to compromise so much and in such an innocuous manner. `spin` is an extremely widely used crate, and a lot of the Rust ecosystem depends on it: as its most active maintainer, I have a duty of care to the crate's users.

**Comment by zesterer** [comment]
I don't necessarily think the pull request should be closed: I'm sure it would be useful others to use your branch or add to the discussion to try to find a way around this issue.

**Comment by notgull** [comment]
Given that #120 is merged, shouldn't this PR be closed?

**Comment by zesterer** [comment]
Yes

**Pull request closed without merging**
